### ISSUE TITLE
Workbook  - Published separately

### ISSUE THREAD

**Issue by michaljak** [bryantbhowell/tableau_tools#27]
Hi 
I am a beginner tableau developer. I have a question how to publish a workbook with separately data source using Tableau REST API. I'm using source control so the tbwx and tde files are on the disk. Do you have a step-by-step example of how to do this?

Best regards,
Michael

**Comment by bryanthowell-tableau** [comment]
There are a couple of aspects to this. Tableau Server has a concept of Published Data Sources, which are data sources that have been published separately from a workbook to the Tableau Server. A workbook can connect to those published data sources, but that connection must occur in Desktop the first time. After that point, you can republish the workbook and the published data source using the REST API. 

It is also possible using tableau_tools to switch WHICH published data source a workbook is connected to, if the second published data source has the same column names and data types (basically a copy or variation).

If you have a TWB file that needs local files, such as an Excel or CSV file, you either need to (1) save it as a TWBX in Desktop so that the files are all included in the single archive package (2) Published the data source first from Desktop, so that the workbook is now connected to the Published Data Source, then publish the TWB via the REST API (you can also update the now existing Published Data Source as well via the REST API after it is published the first time).
