### ISSUE TITLE
Tableau_Tools API connection defaults to version 2.8.  Recommended update to tableau_rest_api_connection.py

### ISSUE THREAD

**Issue by edrossy** [bryantbhowell/tableau_tools#31]
tableau_rest_api_connection.py
Line 17 update to:
def __init__(self, server, username, password, site_content_url="", **version=""**):

after line 24 insert another line to set the api_version (right now it defaults to "2.8" no matter what):
**TableauBase.set_tableau_server_version(self, version)**

This now lets you determine which API to use when making call:
TableauRestApiConnection(server, username, password, site_content_url=site, **version=ver**)

**Comment by bryanthowell-tableau** [comment]
Hi,
This is actually an intentional design -- rather than setting version value within the original TableauRestApiConnection class, you should actually use the appropriate descendant class that represents that API level -- TableauRestApiConnection28 , TableauRestApiConnection31 , etc. Each of the descendant classes implements the added or changed functionality in that version of the API.
